GET http://localhost:5000/usuarios
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTYzODYzODgwOCwianRpIjoiNDFlNTc1MmUtMzczMi00MzZlLWFmYjQtNTFlZjM4NzY2MWM5IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MSwibmJmIjoxNjM4NjM4ODA4LCJleHAiOjE2Mzg2Mzk3MDh9.wv4Ii4FeJmTN5yiqUJ7DXwtW2cHntRqA083qASqApZY